config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/404" => "home#four_oh_four", :via => :all

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user", :format => /html|json|rss/
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login", :format => /html|json/
    post "/logout" => "login#logout"
    get "/login/2fa" => "login#twofa"
    post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss|json/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      get "suggest"
      post "suggest", :action => "submit_suggestions"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"

        post "dragon"
        post "undragon"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/c/:id" => "comments#redirect_from_short_id"
    get "/c/:id.json" => "comments#show_short_id", :format => "json"

    # deprecated
    get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user", :format => /html|json/

    post "/users/:username/ban" => "users#ban", :as => "user_ban"
    post "/users/:username/unban" => "users#unban", :as => "user_unban"
    post "/users/:username/disable_invitation" => "users#disable_invitation", :as => "user_disable_invite"
    post "/users/:username/enable_invitation" => "users#enable_invitation", :as => "user_enable_invite"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"
    get "/settings/2fa" => "settings#twofa", :as => "twofa"
    post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
    get "/settings/2fa_enroll" => "settings#twofa_enroll",
      :as => "twofa_enroll"
    get "/settings/2fa_verify" => "settings#twofa_verify",
      :as => "twofa_verify"
    post "/settings/2fa_update" => "settings#twofa_update",
      :as => "twofa_update"

    post "/settings/pushover_auth" => "settings#pushover_auth"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    get "/settings/github_auth" => "settings#github_auth"
    get "/settings/github_callback" => "settings#github_callback"
    post "/settings/github_disconnect" => "settings#github_disconnect"
    get "/settings/twitter_auth" => "settings#twitter_auth"
    get "/settings/twitter_callback" => "settings#twitter_callback"
    post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    get "/tags" => "tags#index"
    get "/tags.json" => "tags#index", :format => "json"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/hats" => "hats#index"
    get "/hats/build_request" => "hats#build_request",
      :as => "request_hat"
    post "/hats/create_request" => "hats#create_request",
      :as => "create_hat_request"
    get "/hats/requests" => "hats#requests_index"
    post "/hats/approve_request/:id" => "hats#approve_request",
      :as => "approve_hat_request"
    post "/hats/reject_request/:id" => "hats#reject_request",
      :as => "reject_hat_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
    get "/chat" => "home#chat"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :require_logged_in_user

  TOTP_SESSION_TIMEOUT = (60 * 15)

  def index
    @title = t('.accountsettings')

    @edit_user = @user.dup
  end

  def delete_account
    if @user.try(:authenticate, params[:user][:password].to_s)
      @user.delete!
      reset_session
      flash[:success] = t('.deleteaccountflash')
      return redirect_to "/"
    end

    flash[:error] = t('.verifypasswordflash')
    return redirect_to settings_path
  end

  def update
    @edit_user = @user.clone

    if params[:user][:password].empty? ||
    @user.authenticate(params[:current_password].to_s)
      if @edit_user.update_attributes(user_params)
        flash.now[:success] = t('.updatesettingsflash')
        @user = @edit_user
      end
    else
      flash[:error] = t('.passwordnotcorrect')
    end

    render :action => "index"
  end

  def twofa
    @title = t('.title')
  end

  def twofa_auth
    if @user.authenticate(params[:user][:password].to_s)
      session[:last_authed] = Time.now.to_i
      session.delete(:totp_secret)

      if @user.has_2fa?
        @user.disable_2fa!
        flash[:success] = t('.2fahasbeendisabled')
        return redirect_to "/settings"
      else
        return redirect_to twofa_enroll_url
      end
    else
      flash[:error] = t('.2fapassnotcorrect')
      return redirect_to twofa_url
    end
  end

  def twofa_enroll
    @title = t('.title')

    if (Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT
      flash[:error] = t('.enrollmenttimeout')
      return redirect_to twofa_url
    end

    if !session[:totp_secret]
      session[:totp_secret] = ROTP::Base32.random_base32
    end

    totp = ROTP::TOTP.new(session[:totp_secret],
      :issuer => Rails.application.name)
    totp_url = totp.provisioning_uri(@user.email)

    # no option for inline svg, so just strip off leading <?xml> tag
    qrcode = RQRCode::QRCode.new(totp_url)
    qr = qrcode.as_svg(:offset => 0, color: "000", :module_size => 5,
      :shape_rendering => "crispEdges").gsub(/^<\?xml.*>/, "")

    @qr_svg = "<a href=\"#{totp_url}\">#{qr}</a>"
  end

  def twofa_verify
    @title = t('.title')

    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
    !session[:totp_secret]
      flash[:error] = t('.enrollmenttimeout')
      return redirect_to twofa_url
    end
  end

  def twofa_update
    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
    !session[:totp_secret]
      flash[:error] = t('.enrollmenttimeout')
      return redirect_to twofa_url
    end

    @user.totp_secret = session[:totp_secret]
    if @user.authenticate_totp(params[:totp_code])
      # re-roll, just in case
      @user.session_token = nil
      @user.save!

      session[:u] = @user.session_token

      flash[:success] = t('.2fahasbeenenabled')
      session.delete(:totp_secret)
      return redirect_to "/settings"
    else
      flash[:error] = t('.totpinvalid')
      return redirect_to twofa_verify_url
    end
  end

  # external services

  def pushover_auth
    if !Pushover.SUBSCRIPTION_CODE
      flash[:error] = "This site is not configured for Pushover"
      return redirect_to "/settings"
    end

    session[:pushover_rand] = SecureRandom.hex

    return redirect_to Pushover.subscription_url({
      :success => "#{Rails.application.root_url}settings/pushover_callback?" <<
        "rand=#{session[:pushover_rand]}",
      :failure => "#{Rails.application.root_url}settings/",
    })
  end

  def pushover_callback
    if !session[:pushover_rand].to_s.present?
      flash[:error] = "No random token present in session"
      return redirect_to "/settings"
    end

    if !params[:rand].to_s.present?
      flash[:error] = "No random token present in URL"
      return redirect_to "/settings"
    end

    if params[:rand].to_s != session[:pushover_rand].to_s
      raise "rand param #{params[:rand].inspect} != " <<
        session[:pushover_rand].inspect
    end

    @user.pushover_user_key = params[:pushover_user_key].to_s
    @user.save!

    if @user.pushover_user_key.present?
      flash[:success] = "Your account is now setup for Pushover notifications."
    else
      flash[:success] = "Your account is no longer setup for Pushover " <<
        "notifications."
    end

    return redirect_to "/settings"
  end

  def github_auth
    session[:github_state] = SecureRandom.hex
    return redirect_to Github.oauth_auth_url(session[:github_state])
  end

  def github_callback
    if !session[:github_state].present? || !params[:code].present? ||
    (params[:state].to_s != session[:github_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:github_state)

    tok, username = Github.token_and_user_from_code(params[:code])
    if tok.present? && username.present?
      @user.github_oauth_token = tok
      @user.github_username = username
      @user.save!
      flash[:success] = "Your account has been linked to GitHub user " <<
        "#{username}."
    else
      return github_disconnect
    end

    return redirect_to "/settings"
  end

  def github_disconnect
    @user.github_oauth_token = nil
    @user.github_username = nil
    @user.save!
    flash[:success] = "Your GitHub association has been removed."
    return redirect_to "/settings"
  end

  def twitter_auth
    session[:twitter_state] = SecureRandom.hex
    return redirect_to Twitter.oauth_auth_url(session[:twitter_state])
  end

  def twitter_callback
    if !session[:twitter_state].present? ||
    (params[:state].to_s != session[:twitter_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:twitter_state)

    tok, sec, username = Twitter.token_secret_and_user_from_token_and_verifier(
      params[:oauth_token], params[:oauth_verifier])
    if tok.present? && username.present?
      @user.twitter_oauth_token = tok
      @user.twitter_oauth_token_secret = sec
      @user.twitter_username = username
      @user.save!
      flash[:success] = "Your account has been linked to Twitter user @" <<
        "#{username}."
    else
      return twitter_disconnect
    end

    return redirect_to "/settings"
  end

  def twitter_disconnect
    @user.twitter_oauth_token = nil
    @user.twitter_username = nil
    @user.twitter_oauth_token_secret = nil
    @user.save!
    flash[:success] = "Your Twitter association has been removed."
    return redirect_to "/settings"
  end

private

  def user_params
    params.require(:user).permit(
      :username, :email, :password, :password_confirmation, :about,
      :email_replies, :email_messages, :email_mentions,
      :pushover_replies, :pushover_messages, :pushover_mentions,
      :mailing_list_mode, :show_avatars, :show_story_previews,
      :show_submitted_story_threads, :hide_dragons
    )
  end
end

app/views/settings/index.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/u/<%= @user.username %>"><%= t('.viewprofile') %></a>
     |
     <%= link_to t('.logoutlink'), { :controller => "login", :action => "logout" },
       :data => { :confirm => t('.confirmlogoutlink') },
       :method => "post" %>
  </div>
  <div class="legend">
    <%= t('.accountsettings') %>
  </div>

  <%= form_for @edit_user, :url => settings_path, :method => :post,
  :html => { :id => "edit_user" } do |f| %>
    <%= error_messages_for f.object %>

    <div class="boxline">
      <%= f.label :username, t('.username'), :class => "required" %>
      <%= f.text_field :username, :size => 15 %>
      <span class="hint">
        <tt><%= User.username_regex_s %></tt>
      </span>
    </div>

    <div class="boxline">
      <%= label_tag :current_password, t('.currentpassword'),
        :class => "required" %>
      <%= password_field_tag :current_password, nil, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :password, t('.password'), :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :password_confirmation, t('.confirmpassword'),
        :class => "required" %>
      <%= f.password_field :password_confirmation, :size => 40,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :email, t('.emailaddress'), :class => "required" %>
      <%= f.email_field :email, :size => 40 %>
      <span class="hint">
        <%= raw(t('.gravatarized')) %>
      </span>
    </div>

    <div class="boxline">
      <%= f.label :about, t('.about'), :class => "required" %>
      <%= f.text_area :about, :size => "100x5", :style => "width: 600px;" %>
    </div>

    <div class="box">
      <div class="boxline markdown_help_toggler" style="margin-left: 9em;
      width: 600px;">
        <div class="markdown_help_label">
          <%= t('.markdownformattingavailable') %>
        </div>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp" %>
      </div>
    </div>

    <p>
    <%= f.submit t('.saveaccountsettings') %>
    </p>

    <br>

    <div class="legend">
      <%= t('.securitysettings') %>
    </div>

    <div class="boxline">
      <%= f.label :twofa, t('.twofactorauth'), :class => "required" %>
      <span>
      <% if @edit_user.totp_secret.present? %>
        <span style="color: green; font-weight: bold;">
          <%= t('.enabled2fa') %>
        </span> (<a href="/settings/2fa"><%= t('.disable2fa') %></a>)
      <% else %>
        <%= t('.disabled2fa') %> (<a href="/settings/2fa"><%= t('.enroll2fa') %></a>)
      <% end %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.commentreplynotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_replies, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_replies %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_replies,  t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_replies %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.commentmentionnotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_mentions, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_mentions %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_mentions, t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_mentions %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.privatemessagenotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_messages, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_messages %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_messages, t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_messages %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.submittedstorycommentsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :show_submitted_story_threads,
        raw(t('.showyourthreads')),
        :class => "required" %>
      <%= f.check_box :show_submitted_story_threads %>
    </div>

    <br>

    <div class="legend">
      <%= t('.mailinglistsettings') %>
    </div>

    <p>
    <%= raw(t('.mailinglisttext')) %>
    </p>

    <div class="boxline">
      <%= f.label :mailing_list_mode, t('.receivelistemails'),
        :class => "required" %>
      <%= f.select :mailing_list_mode, [ [ t('.listemailoption1'), 0 ],
        [ t('.listemailoption2'), 1 ], [ t('.listemailoption3'), 2 ] ] %>
    </div>

    <div class="boxline">
      <label class="required"><%= t('.listaddress') %></label>
      <span>
      <tt><%= Rails.application.shortname %>-<%=
        @edit_user.mailing_list_token %>@<%= Rails.application.domain %></tt>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.miscsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :show_story_previews, t('.storypreview'),
        :class => "required" %>
      <%= f.check_box :show_story_previews %>
    </div>

    <div class="boxline">
      <%= f.label :show_avatars, t('.useravatars'), :class => "required" %>
      <%= f.check_box :show_avatars %>
    </div>

    <div class="boxline">
      <%= f.label :hide_dragons, t('.hidedragons'), :class => "required" %>
      <%= f.check_box :hide_dragons %>
    </div>

    <br>
    <%= f.submit t('.saveallsettings') %>
  <% end %>

  <br>
  <br>

  <div class="legend">
    <%= t('.externalaccounts') %>
  </div>

  <% if Pushover.enabled? %>
    <div class="boxline">
      <%= label_tag :pushover_user_key,
        raw("<a href=\"https://pushover.net/\">Pushover</a>:"),
        :class => "required" %>
      <%= link_to((@edit_user.pushover_user_key.present??
        "Manage Pushover Subscription" : "Subscribe With Pushover"),
        "/settings/pushover_auth", :class => "pushover_button",
        :method => :post) %>
      <span class="hint">
        For optional comment and message notifications above
      </span>
    </div>
  <% end %>

  <% if Github.enabled? %>
    <div class="boxline">
      <%= label_tag :github_username, "GitHub:", :class => "required" %>
      <% if @edit_user.github_username.present? %>
        Linked to
        <strong><a href="https://github.com/<%= h(@edit_user.github_username)
          %>"><%= h(@edit_user.github_username) %></a></strong>
          (<%= link_to "Disconnect", "/settings/github_disconnect",
            :method => :post %>)
      <% else %>
        <a href="/settings/github_auth">Connect</a>
      <% end %>
    </div>
  <% end %>

  <% if Twitter.enabled? %>
    <div class="boxline">
      <%= label_tag :twitter_username, "Twitter:", :class => "required" %>
      <% if @edit_user.twitter_username.present? %>
        Linked to
        <strong><a href="https://twitter.com/<%= h(@edit_user.twitter_username)
          %>">@<%= h(@edit_user.twitter_username) %></a></strong>
          (<%= link_to "Disconnect", "/settings/twitter_disconnect",
            :method => :post %>)
      <% else %>
        <a href="/settings/twitter_auth">Connect</a>
      <% end %>
    </div>
  <% end %>

  <br>
  <br>

  <a name="invite"></a>
  <div class="legend">
    <%= t('.inviteuser') %>
  </div>

  <% if @user.can_invite? %>
    <%= render :partial => "users/invitationform" %>
  <% else %>
      <%= t('.cannotsendinvitations') %>
  <% end %>

  <br>
  <br>

  <%= form_for @edit_user, :url => delete_account_path, :method => :post,
  :html => { :id => "delete_user" } do |f| %>
    <div class="legend">
      <%= t('.deleteaccount') %>
    </div>

    <p>
    <%= t('.deleteaccounttext') %>
    </p>

    <div class="boxline">
      <%= f.label :password,  t('.verifypassword'), :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <br>
    <%= f.submit t('.deleteaccountconfirmation') %>
  <% end %>
</div>

app/views/settings/twofa.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings"><%= t('.backtosettings') %></a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_for @user, :url => twofa_auth_url, :method => :post do |f| %>
    <p>
    <% if @user.has_2fa? %>
      <%= t('.turnoff') %>
    <% else %>
      <%= t('.turnon') %>
    <% end %>
    </p>

    <div class="boxline">
      <%= f.label :password, t('.currentpassword'), :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <p>
    <% if @user.has_2fa? %>
      <%= submit_tag t('.disable2fa') %>
    <% else %>
      <%= submit_tag t('.continue') %>
    <% end %>
  <% end %>
</div>

app/views/settings/twofa_enroll.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings"><%= t('.backtosettings') %></a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <p>
  <%= raw(t('.scanqrcode')) %>
  </p>

  <%= raw @qr_svg %>

  <p>
  <%= t('.registring') %>
  </p>

  <p>
  <%= button_to t('.verifyenable'), twofa_verify_url, :method => :get %>
</div>

app/views/settings/twofa_verify.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_tag twofa_update_url do %>
    <p>
    <%= t('.enablecode') %>
    </p>

    <div class="boxline">
      <%= label_tag :totp_code, "TOTP Code:", :class => "required" %>
      <%= number_field_tag :totp_code, "", :size => 10, :autocomplete => "off",
          :autofocus => true, :class => "totp_code" %>
    </div>

    <p>
    <%= submit_tag t('.verifyenable') %>
  <% end %>
</div>